### ISSUE TITLE
error with controlnet model chosen in axis1

### ISSUE THREAD

**Issue by choigawoon** [mcmonkeyprojects/sd-infinity-grid-generator-script#113]
```python
Traceback (most recent call last):█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 15.26it/s]
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/future/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/future/stable-diffusion-webui/extensions/sd-infinity-grid-generator-script/scripts/infinity_grid.py", line 411, in fill_axis
    return ", ".join(list(mode.valid_list()))
  File "/home/future/stable-diffusion-webui/extensions/sd-infinity-grid-generator-script/scripts/infinity_grid.py", line 202, in <lambda>
    registerMode("[ControlNet] Model", GridSettingMode(dry=True, type="text", apply=apply_field("control_net_model"), clean=validate_param, valid_list=lambda: list(list(module.cn_models.keys()))))
AttributeError: module 'controlnet.py' has no attribute 'cn_models'
```
stable diffusion webui : 1.6

how can i use with controlnet?

![image](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/3104530/18c45c40-590d-4059-a57a-464884c504c3)

![image](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/3104530/2796a449-d667-43c3-a7f1-183fdf4a14d9)

**Comment by senelya** [comment]
Found problem. Think that fixed it (atleast it works for me)
https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/125

line 204 changed to:
registerMode("[ControlNet] Model", GridSettingMode(dry=True, type="text", apply=apply_field("control_net_model"), clean=validate_param, valid_list=lambda: list(list(module.global_state.cn_models.keys()))))

**Comment by mcmonkey4eva** [comment]
Nice! Thanks senelya!

**Comment by senelya** [comment]
I`m happy! it is my first commit and contribution! U are so great and made such nice thing!
