### ISSUE TITLE
UI broken after latest controlnet update

### ISSUE THREAD

**Issue by heftig** [mcmonkeyprojects/sd-infinity-grid-generator-script#135]
After updating [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) from [bbcae30](https://github.com/Mikubill/sd-webui-controlnet/commit/bbcae309d1c0921c212bfb9719169db8826b795f) to [282c619](https://github.com/Mikubill/sd-webui-controlnet/commit/282c619696093ffe7ae10b59af2a93540a4c716f), the infinity grid extension fails to load:

```
*** Error calling: C:\Users\janst\AI\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py/ui
    Traceback (most recent call last):
      File "C:\Users\janst\AI\stable-diffusion-webui\modules\scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\janst\AI\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 351, in ui
        try_init()
      File "C:\Users\janst\AI\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 196, in try_init
        preprocessors_list = script_list[0].script_class().preprocessor.keys()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'Script' object has no attribute 'preprocessor'
```

**Comment by heftig** [comment]
This seems to work and load the list of preprocessors, but I haven't tested if it also applies controlnet parameters correctly.

```diff
diff --git a/scripts/infinity_grid.py b/scripts/infinity_grid.py
index 37d9511..eaea87a 100644
--- a/scripts/infinity_grid.py
+++ b/scripts/infinity_grid.py
@@ -192,16 +192,14 @@ def try_init():
             registerMode("[DynamicThreshold] Separate Feature Channels", GridSettingMode(dry=True, type="boolean", apply=apply_field("dynthres_separate_feature_channels")))
         script_list = [x for x in scripts.scripts_data if x.script_class.__module__ == "controlnet.py"][:1]
         if len(script_list) == 1:
-            # Hacky but works
-            preprocessors_list = script_list[0].script_class().preprocessor.keys()
-            module = script_list[0].module
+            controlnet = script_list[0].module
             def validate_param(p, v):
                 if not shared.opts.data.get("control_net_allow_script_control", False):
                     raise RuntimeError("ControlNet options cannot currently work, you must enable 'Allow other script to control this extension' in Settings -> ControlNet first")
                 return v
             registerMode("[ControlNet] Enable", GridSettingMode(dry=True, type="boolean", apply=apply_field("control_net_enabled"), clean=validate_param))
-            registerMode("[ControlNet] Preprocessor", GridSettingMode(dry=True, type="text", apply=apply_field("control_net_module"), clean=validate_param, valid_list=lambda: list(preprocessors_list)))
-            registerMode("[ControlNet] Model", GridSettingMode(dry=True, type="text", apply=apply_field("control_net_model"), clean=validate_param, valid_list=lambda: list(list(module.global_state.cn_models.keys()))))
+            registerMode("[ControlNet] Preprocessor", GridSettingMode(dry=True, type="text", apply=apply_field("control_net_module"), clean=validate_param, valid_list=lambda: list(p.name for p in controlnet.Preprocessor.get_sorted_preprocessors())))
+            registerMode("[ControlNet] Model", GridSettingMode(dry=True, type="text", apply=apply_field("control_net_model"), clean=validate_param, valid_list=lambda: list(controlnet.global_state.cn_models.keys())))
             registerMode("[ControlNet] Weight", GridSettingMode(dry=True, type="decimal", min=0.0, max=2.0, apply=apply_field("control_net_weight"), clean=validate_param))
             registerMode("[ControlNet] Guidance Strength", GridSettingMode(dry=True, type="decimal", min=0.0, max=1.0, apply=apply_field("control_net_guidance_strength"), clean=validate_param))
             registerMode("[ControlNet] Annotator Resolution", GridSettingMode(dry=True, type="integer", min=0, max=2048, apply=apply_field("control_net_pres"), clean=validate_param))
```

**Comment by mcmonkey4eva** [comment]
I expect the above commit should suffice -- I also made the error check more generic so it hopefully shouldn't kill the whole script if anything goes wrong again, just the extension compat
