### ISSUE TITLE
AttributeError: 'FakeInitialModel' object has no attribute 'sd_checkpoint_info' on ForgeUI

### ISSUE THREAD

**Issue by coldasicee** [mcmonkeyprojects/sd-infinity-grid-generator-script#151]
I'm getting the error "AttributeError: 'FakeInitialModel' object has no attribute 'sd_checkpoint_info'" when trying to generate.

Here is cmd reply:

> Have 192 unique value sets, will go into outputs\txt2img-grids/autonamed_inf_grid_2024_10_19_16_18_35
> Skipped 0 files, will run 192 files, for 3840 total steps
> Building final web data...
> Traceback (most recent call last):
>   File "C:\stablediffusion\forge2\webui\modules_forge\main_thread.py", line 30, in work
>     self.result = self.func(*self.args, **self.kwargs)
>   File "C:\stablediffusion\forge2\webui\modules\txt2img.py", line 120, in txt2img_function
>     processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
>   File "C:\stablediffusion\forge2\webui\modules\scripts.py", line 792, in run
>     processed = script.run(p, *script_args)
>   File "C:\stablediffusion\forge2\webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 475, in run
>     result = core.run_grid_gen(p, grid_file, p.outpath_grids, output_file_path, do_overwrite, fast_skip, generate_page, publish_gen_metadata, dry_run, manual_axes, skip_invalid=skip_invalid)
>   File "C:\stablediffusion\forge2\webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 756, in run_grid_gen
>     json = WebDataBuilder.emit_web_data(folder, grid, publish_gen_metadata, pass_through_obj, yaml_content, dry_run)
>   File "C:\stablediffusion\forge2\webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 670, in emit_web_data
>     json = WebDataBuilder.build_json(grid, publish_gen_metadata, p, dry_run)
>   File "C:\stablediffusion\forge2\webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 569, in build_json
>     result['metadata'] = None if webdata_get_base_param_data is None else webdata_get_base_param_data(p)
>   File "C:\stablediffusion\forge2\webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 304, in a1111_webdata_get_base_param_data
>     "model": choose_better_file_name('', shared.sd_model.sd_checkpoint_info.model_name).replace(',', '').replace(':', ''),
> AttributeError: 'FakeInitialModel' object has no attribute 'sd_checkpoint_info'
> 'FakeInitialModel' object has no attribute 'sd_checkpoint_info'

I'm also attaching the settings I chose for the grid:
![image](https://github.com/user-attachments/assets/de051f3a-0323-4889-a5f5-15e4a45cd7d8)

Btw, I have a model selected and it generates fine without the script enabled. Any way to fix this?

**Comment by inmanuscript** [comment]
How about trying to delete the \extensions\sd-infinity-grid-generator-script\scripts\__pycache__ folder?

It worked for me in my environment.
But, I feel like model switching might not be possible on Forge.

**Comment by gootscootboogie** [comment]
Got it working!!! This drove me nuts while trying to troubleshoot it for several hours. 

Go to this folder `\extensions\sd-infinity-grid-generator-script\scripts`:

Edit the infinity_grid.py file with your text editor of choice and [go to line 304](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/blob/0082d79eb9a45a6a55e92e9beeaf5f8c72d8ad8a/scripts/infinity_grid.py#L304).  It should look like this:
> "model": choose_better_file_name('', shared.sd_model.sd_checkpoint_info.model_name).replace(',', '').replace(':', ''),

Change the value to opts.sd_model_checkpoint and save your changes:
> "model": opts.sd_model_checkpoint,

If you already have ForgeUI running, end the running process along with closing the local web page.  Relaunch ForgeUI and hopefully that should do the trick 🙏

**Comment by whitesky1226** [comment]
> Got it working!!! This drove me nuts while trying to troubleshoot it for several hours.
> 
> Go to this folder `\extensions\sd-infinity-grid-generator-script\scripts`:
> 
> Edit the infinity_grid.py file with your text editor of choice and [go to line 304](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/blob/0082d79eb9a45a6a55e92e9beeaf5f8c72d8ad8a/scripts/infinity_grid.py#L304). It should look like this:
> 
> > "model": choose_better_file_name('', shared.sd_model.sd_checkpoint_info.model_name).replace(',', '').replace(':', ''),
> 
> Change the value to opts.sd_model_checkpoint and save your changes:
> 
> > "model": opts.sd_model_checkpoint,
> 
> If you already have ForgeUI running, end the running process along with closing the local web page. Relaunch ForgeUI and hopefully that should do the trick 🙏

I modified the code according to your method. Error no longer occurs. But during the plugin's operation, it does not load and switch models according to the yaml file I set. Instead, it continues to use the model selected in the top-left corner of ForgeUI. I cannot find out how to fix this😫
