### ISSUE TITLE
Vae issue regarding "KeyError: 'auto'"

### ISSUE THREAD

**Issue by valconius** [mcmonkeyprojects/sd-infinity-grid-generator-script#24]
On any recent webui commit, irrespective of the value of the "vae" parameter in the used yml file, and irrespective of the  vae selected in the webui, and irrespective of whether or not a similar-named vae exists for the checkpoint being used, the following error occurs:
```
Weights loaded in 0.5s.
Error completing request
Arguments: ('task(mbl812qsznt2rax)', '', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 6, 0, 0, 0, 0, 0.25, False, 'LoRA', '', 1, 'LoRA', '', 1, 'LoRA', '', 1, 'LoRA', '', 1, 'LoRA', '', 1, True, False, 1, '', 0, '', True, False, False, False, False, False, False, False, '', 1, '', 0, '', True, False, False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', '<br>Confused/new? View <a style="border-bottom: 1px #00ffff dotted;" href="https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script">the README</a> for usage instructions.<br><br>', False, True, False, True, True, 'crow_prompts0.yml', '🔄', False, False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, 0, 0.0, 10.0, True, 30.0, True, '', False, False, False, False, 'Auto', 0.5, 1, 'fixed', 1, 'linear', '30', 'grad_min', 0.01, 1, 'clip', 1.0, 1.0, 'mp4', 10.0, 0, '', True, 'Euler a', 0.95, 0.75, 'zero', 'pos', 0, -0.002, 5, 0, -0.02, False, 'linear', 0.02, 0.0, 0.5, None) {}
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "/home/user/stable-diffusion-webui/extensions/sd-infinity-grid-generator-script/scripts/infinity_grid.py", line 691, in run
    result = runner.run(dry_run)
  File "/home/user/stable-diffusion-webui/extensions/sd-infinity-grid-generator-script/scripts/infinity_grid.py", line 461, in run
    set.applyTo(p, dry)
  File "/home/user/stable-diffusion-webui/extensions/sd-infinity-grid-generator-script/scripts/infinity_grid.py", line 394, in applyTo
    mode["apply"](p, val)
  File "/home/user/stable-diffusion-webui/extensions/sd-infinity-grid-generator-script/scripts/infinity_grid.py", line 111, in applyVae
    sd_vae.reload_vae_weights(None, sd_vae.vae_dict[vaeName])
KeyError: 'auto'
```
I provisionally worked around this issue by changing the relevant function to something like:
```
def applyVae(p, v):
    sd_vae.reload_vae_weights(None, sd_vae.vae_dict['kl-f8-anime2.ckpt'])
```
Of course this is a hardcoded vae. Specifying this manually in the yml file seems to do nothing, which is strange. Most people probably wind up using the exact same vae for every single checkpoint so it's not like it matters, but I do wonder why this occurs.

As an aside, do you know of any easier way to reload extensions and scripts for webui other than manually killing the webui process and re-launching it? I couldn't get webui to accept the above change until I did so.

**Comment by mcmonkey4eva** [comment]
Yep, WebUI updated to change how VAEs are handled internally.
Pushed a commit that works as intended on the new WebUI version.

Re your side question: theoretically settings -> actions has reload options and extensions -> "apply and restart" too, but in practice those are usually pretty shifty. I've gotten used to having to close and restart the webui when testing changes.
