### ISSUE TITLE
UI Error: Uncaught DOMException: Failed to execute 'querySelector' on 'Document'

### ISSUE THREAD

**Issue by agilly1989** [mcmonkeyprojects/sd-infinity-grid-generator-script#30]
On selection of the model I have, I am getting the console error
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#tab_models__models\abyssorangemix2_sfw_safetensors\abyssorangemix2_sfw.safetensors_[038ba203d8]' is not a valid selector.
    at n (file:///C:/Users/geek_/OneDrive/Desktop/Python%20on%20C/stable-diffusion-webui/outputs/txt2img-grids/peach-castle/bootstrap.bundle.min.js:6:605)
    at kn._deactivate (file:///C:/Users/geek_/OneDrive/Desktop/Python%20on%20C/stable-diffusion-webui/outputs/txt2img-grids/peach-castle/bootstrap.bundle.min.js:6:75461)
    at kn.show (file:///C:/Users/geek_/OneDrive/Desktop/Python%20on%20C/stable-diffusion-webui/outputs/txt2img-grids/peach-castle/bootstrap.bundle.min.js:6:75045)
    at HTMLAnchorElement.<anonymous> (file:///C:/Users/geek_/OneDrive/Desktop/Python%20on%20C/stable-diffusion-webui/outputs/txt2img-grids/peach-castle/bootstrap.bundle.min.js:6:77604)
    at HTMLDocument.n (file:///C:/Users/geek_/OneDrive/Desktop/Python%20on%20C/stable-diffusion-webui/outputs/txt2img-grids/peach-castle/bootstrap.bundle.min.js:6:4135)
```
![image](https://user-images.githubusercontent.com/50060406/215297871-309a1f62-b714-4cdc-9769-c6d51adf2d90.png)
![image](https://user-images.githubusercontent.com/50060406/215297875-9f643a1d-0dbe-4158-89f5-716f9fecf5a6.png)
Having the model as a (super) Axis works fine, its just the tabs

I will investigate what I can do on this end but JS isn't something I am knowledgeable in

**Comment by mcmonkey4eva** [comment]
I think this is because of the dirty tab names, with `[]` and all on em.
For the record you can just do `AbyssOrangeMix2_hard` and it should get the correct model from just that. Including a bit more of the path doesn't hurt, but adding the hash is entirely redundant if not outright wrong.

**Comment by mcmonkey4eva** [comment]
oh, yeah, not a bug, you have your *data keys* set to those wild values. Those can be any text, even just `1:`, `2:`, etc.
