### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by kuso-ge** [mcmonkeyprojects/sd-infinity-grid-generator-script#78]
Can't seem to use non-unicode characters like this: `<lora:飞翔真琴:0.7> kowata makoto||`
for prompt replace 
![image](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/12083007/29ab186b-c2e0-44d2-aed1-85167f18d9af)

```

Traceback (most recent call last):
      File "D:\AI\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\AI\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\AI\automatic1111\stable-diffusion-webui\modules\txt2img.py", line 54, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\AI\automatic1111\stable-diffusion-webui\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
      File "D:\AI\automatic1111\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 433, in run
        result = core.run_grid_gen(p, grid_file, p.outpath_grids, output_file_path, do_overwrite, fast_skip, generate_page, publish_gen_metadata, dry_run, manual_axes)
      File "D:\AI\automatic1111\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 699, in run_grid_gen
        json = WebDataBuilder.emit_web_data(folder, grid, publish_gen_metadata, pass_through_obj, yaml_content, dry_run)
      File "D:\AI\automatic1111\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 639, in emit_web_data
        f.write(html)
    UnicodeEncodeError: 'cp932' codec can't encode character '\u98de' in position 323888: illegal multibyte sequence

---
```

**Comment by kuso-ge** [comment]
passing `encoding="utf-8"` on open() calls seems to fix the issue.

i.e:
`open(path + '/last.js', 'w', encoding="utf-8")`

**Comment by mcmonkey4eva** [comment]
Oops, good find - fixed!
